# Generated by Django 4.2.25 on 2025-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
