# Generated by Django 4.2.25 on 2025-11-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="planned_start_date",
            field=models.DateField(
                blank=True,
                help_text="Planned start date for weld production.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="planned_welds_per_workday",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Planned weld count per productive workday.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_total_weld_inches",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total weld inches planned for the project scope.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="workdays_per_week",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of planned workdays per calendar week.",
                null=True,
            ),
        ),
    ]
