# Generated by Django 4.2.25 on 2025-11-13 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_status_and_roles(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectMember = apps.get_model("projects", "ProjectMember")

    archived_ids = list(
        Project.objects.filter(is_archived=True).values_list("id", flat=True)
    )
    if archived_ids:
        Project.objects.filter(id__in=archived_ids).update(status="ARCHIVED")
    Project.objects.exclude(id__in=archived_ids).update(status="ACTIVE")

    ProjectMember.objects.filter(role="MANAGER").update(role="PROJECT_MANAGER")

    manager_memberships = ProjectMember.objects.filter(
        role="PROJECT_MANAGER"
    ).values_list("project_id", "user_id")
    for project_id, user_id in manager_memberships:
        Project.objects.filter(id=project_id, project_manager__isnull=True).update(
            project_manager_id=user_id
        )


def backwards_status_and_roles(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectMember = apps.get_model("projects", "ProjectMember")
    Project.objects.update(status="PLANNED")
    ProjectMember.objects.filter(role="PROJECT_MANAGER").update(role="MANAGER")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0003_project_planned_start_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_unarchive_project", "Can unarchive archived projects")
                ],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="client_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short description of the project.", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="external_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="planned_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional internal project code",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quality_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quality_managed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quality_techs",
            field=models.ManyToManyField(
                blank=True,
                related_name="quality_tech_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="site_address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="site_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="site_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("ACTIVE", "Active"),
                    ("ON_HOLD", "On hold"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="PLANNED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="superintendent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superintended_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("PROJECT_MANAGER", "Project Manager"),
                    ("SUPERINTENDENT", "Superintendent"),
                    ("QUALITY_MANAGER", "Quality Manager"),
                    ("QUALITY_TECH", "Quality Tech"),
                    ("MEMBER", "Member"),
                    ("GUEST", "Guest"),
                ],
                default="MEMBER",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.tag"
            ),
        ),
        migrations.RunPython(
            forwards_status_and_roles, backwards_status_and_roles
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_archived",
        ),
    ]
