# Generated by Django 4.2.25 on 2025-11-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0004_tag_alter_project_options_remove_project_is_archived_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="planned_weld_inches_per_workday",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Planned weld inches per productive workday.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="planned_welds_per_workday",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Deprecated: planned weld count per productive workday.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
