# Generated by Django 4.2.25 on 2025-10-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('GUEST', 'Guest')], default='MEMBER', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='organizations.organization'),
        ),
    ]
