# Generated by Django 4.2.25 on 2025-10-17 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_alter_invitation_role_alter_membership_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('DRAWING', 'Drawing'), ('MTR', 'Material Test Report'), ('WPS', 'Welding Procedure Spec'), ('NDE', 'NDE Report'), ('COATING', 'Coating Report'), ('TORQUE', 'Torque Report'), ('OTHER', 'Other')], max_length=16)),
                ('number', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('file', models.FileField(upload_to='docs/%Y/%m/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_type', 'number', '-version'],
                'unique_together': {('org', 'doc_type', 'number', 'version')},
            },
        ),
    ]
