# Generated by Django 4.2.25 on 2025-11-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("NDE", "NDE Report"),
                    ("INSPECTOR", "Inspector Qualification"),
                    ("WELDER", "Welder Qualification"),
                    ("MTR", "MTR"),
                    ("WPS", "WPS"),
                    ("CALIBRATION", "Calibration"),
                ],
                max_length=16,
            ),
        ),
    ]
