# Generated by Django 4.2.25 on 2025-11-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drive', '0007_filenode_document_fields'),
        ('documents', '0003_drop_document_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
            ],
            options={
                'ordering': ['doc_type', 'number', '-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('drive.filenode',),
        ),
    ]
