# Generated by Django 4.2.25 on 2025-10-19 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_alter_invitation_role_alter_membership_role_and_more'),
        ('drive', '0002_filenode_project_folder_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('PREVIEW', 'Preview'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload')], max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua', models.CharField(blank=True, max_length=512)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_events', to=settings.AUTH_USER_MODEL)),
                ('file_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='drive.filenode')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_events', to='organizations.organization')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='drive.fileversion')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['file_node', '-at'], name='fe_node_at_desc'), models.Index(fields=['org', '-at'], name='fe_org_at_desc'), models.Index(fields=['action', '-at'], name='fe_action_at')],
            },
        ),
    ]
