# Generated by Django 4.2.25 on 2025-10-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_filenode_checked_out_at_filenode_checked_out_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileevent',
            name='action',
            field=models.CharField(choices=[('VIEW', 'View'), ('PREVIEW', 'Preview'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('CHECKOUT', 'Check-out'), ('CHECKIN', 'Check-in'), ('FORCE_CHECKIN', 'Force check-in')], max_length=16),
        ),
    ]
