# Generated by Django 4.2.25 on 2025-10-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_alter_fileevent_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
