# Generated by Django 4.2.25 on 2025-11-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0008_flatten_project_root_folders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("VIEW", "View"),
                    ("PREVIEW", "Preview"),
                    ("DOWNLOAD", "Download"),
                    ("UPLOAD", "Upload"),
                    ("CHECKOUT", "Check-out"),
                    ("CHECKIN", "Check-in"),
                    ("FORCE_CHECKIN", "Force check-in"),
                    ("REVERT", "Revert"),
                ],
                max_length=16,
            ),
        ),
    ]
