# Generated by Django 4.2.25 on 2025-11-13 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drive", "0009_alter_fileevent_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="filenode",
            name="mtr_approved",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the latest MTR version has been fully verified and approved.",
            ),
        ),
        migrations.AddField(
            model_name="filenode",
            name="mtr_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filenode",
            name="mtr_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_mtr_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filenode",
            name="mtr_approved_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_mtr_for",
                to="drive.fileversion",
            ),
        ),
        migrations.AddIndex(
            model_name="filenode",
            index=models.Index(
                fields=["doc_type", "mtr_approved"], name="drive_file_mtr_approved"
            ),
        ),
        migrations.AddIndex(
            model_name="filenode",
            index=models.Index(
                fields=["mtr_approved_at"], name="drive_file_mtr_approved_at"
            ),
        ),
    ]
