# Generated by ChatGPT on 2025-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0010_filenode_mtr_approved_filenode_mtr_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filenode",
            name="is_kpi_template",
            field=models.BooleanField(
                default=False,
                help_text="Marks this file as the KPI template for access restrictions.",
            ),
        ),
    ]
