# Generated by Django 4.2.25 on 2025-11-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("organizations", "0002_alter_invitation_role_alter_membership_role_and_more"),
        ("welds", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weld",
            name="heat_number",
        ),
        migrations.RemoveField(
            model_name="weld",
            name="joint_type",
        ),
        migrations.RemoveField(
            model_name="weld",
            name="location",
        ),
        migrations.RemoveField(
            model_name="weld",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="weld",
            name="status",
        ),
        migrations.RemoveField(
            model_name="weld",
            name="welder",
        ),
        migrations.RemoveField(
            model_name="weld",
            name="wps",
        ),
        migrations.AddField(
            model_name="weld",
            name="date_welded",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weld",
            name="disposition",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("repair", "Repair"),
                    ("cut_out", "Cut Out"),
                ],
                default="accepted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="disposition_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="weld",
            name="drawing_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="weld",
            name="material1_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="weld",
            name="material1_grade",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="weld",
            name="material1_outer_diameter_in",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="material1_wall_thickness_in",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="material2_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="weld",
            name="material2_grade",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="weld",
            name="material2_outer_diameter_in",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="material2_wall_thickness_in",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="nde_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weld",
            name="nde_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="weld",
            name="weld_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="weld",
            name="welder_stencil_cap",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="weld",
            name="welder_stencil_fill",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="weld",
            name="welder_stencil_fill_additional",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="weld",
            name="welder_stencil_root_hotpass",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="NDERig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nde_rigs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("org", "name")},
            },
        ),
        migrations.CreateModel(
            name="MaterialHeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heat_number", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("material_grade", models.CharField(blank=True, max_length=120)),
                (
                    "outer_diameter_in",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "wall_thickness_in",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("wps_number", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mtr_document",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"doc_type": "MTR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_heats",
                        to="documents.document",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_heats",
                        to="organizations.organization",
                    ),
                ),
                (
                    "wps_document",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"doc_type": "WPS"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_heat_wps",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["heat_number"],
                "unique_together": {("org", "heat_number")},
            },
        ),
        migrations.AddField(
            model_name="weld",
            name="material1_heat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_welds",
                to="welds.materialheat",
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="material2_heat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_welds",
                to="welds.materialheat",
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="nde_rig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="welds",
                to="welds.nderig",
            ),
        ),
    ]
