# Generated by Django 4.2.25 on 2025-11-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0007_filenode_document_fields"),
        ("organizations", "0002_alter_invitation_role_alter_membership_role_and_more"),
        ("projects", "0002_alter_project_is_archived"),
        ("welds", "0004_weld_nde_type_weld_repair_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nderig",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="nderig",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nde_rigs",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="nderig",
            name="qualification_folder",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nde_rig",
                to="drive.folder",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nderig",
            unique_together={("org", "project", "name")},
        ),
        migrations.CreateModel(
            name="Welder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("stencil", models.CharField(max_length=50)),
                ("employee_id", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_wps",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"doc_type": "WPS"},
                        related_name="approved_welders",
                        to="drive.filenode",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welders",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["stencil", "name"],
                "unique_together": {("org", "stencil")},
            },
        ),
        migrations.AddField(
            model_name="weld",
            name="welder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="welds",
                to="welds.welder",
            ),
        ),
    ]
