# Generated by Django 4.2.25 on 2025-11-11 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("welds", "0006_multiple_welders_per_pass"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeldHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("ROLLBACK", "Rollback"),
                        ],
                        max_length=16,
                    ),
                ),
                ("changed_fields", models.JSONField(default=list)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weld_history_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weld",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="welds.weld",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["weld", "-created_at"],
                        name="welds_weldh_weld_id_d7f641_idx",
                    )
                ],
            },
        ),
    ]
