# Generated by Django 4.2.25 on 2025-11-12 14:37

from django.db import migrations, models
import django.db.models.deletion


def populate_weld_metadata(apps, schema_editor):
    Weld = apps.get_model("welds", "Weld")
    Welder = apps.get_model("welds", "Welder")

    welder_lookup = {}
    for welder in Welder.objects.all():
        if welder.stencil:
            welder_lookup[(welder.org_id, welder.stencil.lower())] = welder.id

    weld_qs = Weld.objects.select_related(
        "project",
        "material1_heat",
        "material2_heat",
    )
    for weld in weld_qs.iterator():
        updates = {}
        if weld.weld_date is None and weld.date_welded:
            updates["weld_date"] = weld.date_welded

        primary_stencil = weld.primary_stencil
        if not primary_stencil:
            for field in (
                "welder_stencil_root_hotpass",
                "welder_stencil_fill",
                "welder_stencil_cap",
                "welder_stencil_repair",
            ):
                raw_value = getattr(weld, field, "") or ""
                for candidate in raw_value.split(","):
                    candidate = candidate.strip()
                    if candidate:
                        primary_stencil = candidate
                        updates["primary_stencil"] = candidate
                        break
                if primary_stencil:
                    break

        if primary_stencil and not weld.primary_welder_id and weld.project_id:
            key = (weld.project.org_id, primary_stencil.lower())
            welder_id = welder_lookup.get(key)
            if welder_id:
                updates["primary_welder_id"] = welder_id

        if not weld.heat_number:
            heat = getattr(weld, "material1_heat", None) or getattr(
                weld, "material2_heat", None
            )
            if heat and heat.heat_number:
                updates["heat_number"] = heat.heat_number

        if weld.od is None:
            candidates = [
                getattr(weld, "material1_outer_diameter_in", None),
                getattr(weld, "material2_outer_diameter_in", None),
            ]
            for heat_field in ("material1_heat", "material2_heat"):
                heat_obj = getattr(weld, heat_field, None)
                if heat_obj:
                    candidates.append(getattr(heat_obj, "outer_diameter_in", None))
            for candidate in candidates:
                if candidate is not None:
                    updates["od"] = candidate
                    break

        if not weld.pipe_size:
            if weld.material1_description:
                updates["pipe_size"] = weld.material1_description
            elif weld.material2_description:
                updates["pipe_size"] = weld.material2_description

        if not weld.wps_document_id:
            for heat_field in ("material1_heat", "material2_heat"):
                heat_obj = getattr(weld, heat_field, None)
                if heat_obj and heat_obj.wps_document_id:
                    updates["wps_document_id"] = heat_obj.wps_document_id
                    break

        if updates:
            for field, value in updates.items():
                setattr(weld, field, value)
            weld.save(update_fields=list(updates.keys()))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0007_filenode_document_fields"),
        ("welds", "0008_weldevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeldRepair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repair_date", models.DateField()),
                ("repair_cause", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-repair_date", "-id"],
            },
        ),
        migrations.RenameIndex(
            model_name="weldevent",
            new_name="welds_welde_weld_id_6ae0fc_idx",
            old_name="welds_welde_weld_id_bd96c0_idx",
        ),
        migrations.AddField(
            model_name="weld",
            name="heat_number",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="weld",
            name="od",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Outer diameter in inches.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="pipe_size",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="weld",
            name="primary_stencil",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="weld",
            name="primary_welder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_welds",
                to="welds.welder",
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="weld_date",
            field=models.DateField(
                blank=True,
                help_text="Normalized weld date used for production reporting.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="weld_length_basis",
            field=models.CharField(
                blank=True,
                help_text="Additional notes describing how weld length was derived.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="weld_length_inches",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Canonical measured length of the weld in inches.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="weld_length_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MEASURED", "Measured"),
                    ("STITCH", "Derived from stitch length"),
                    ("STENCIL_AVG", "Stencil average"),
                    ("PROJECT_AVG", "Project average"),
                    ("OD_PI", "Outer diameter circumference"),
                    ("MANUAL", "Manual entry"),
                ],
                help_text="Source used to derive the weld length value.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="wps_document",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"doc_type": "WPS"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="welds",
                to="drive.filenode",
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["project", "weld_length_inches"],
                name="welds_weld_project_9d19c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["project", "weld_date"], name="welds_weld_project_858779_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["heat_number"], name="welds_weld_heat_nu_b50271_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["pipe_size"], name="welds_weld_pipe_si_d0f51d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(fields=["od"], name="welds_weld_od_15c9c2_idx"),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["wps_document"], name="welds_weld_wps_doc_d04ebf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["primary_welder"], name="welds_weld_primary_5fed0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["primary_stencil"], name="welds_weld_primary_7ce219_idx"
            ),
        ),
        migrations.AddField(
            model_name="weldrepair",
            name="weld",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repairs",
                to="welds.weld",
            ),
        ),
        migrations.AddIndex(
            model_name="weldrepair",
            index=models.Index(
                fields=["repair_date"], name="welds_weldr_repair__2ba934_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weldrepair",
            index=models.Index(
                fields=["weld", "repair_date"], name="welds_weldr_weld_id_ff0a42_idx"
            ),
        ),
        migrations.RunPython(populate_weld_metadata, noop),
    ]
