# Generated by Django 4.2.25 on 2025-11-13 22:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_invitation_role_alter_membership_role_and_more"),
        ("welds", "0010_reinspection_repairattempt_weldinspection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NominalPipeOD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=32)),
                ("actual_od", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "tolerance",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.125"),
                        help_text="Allowable +/- tolerance when matching an actual OD.",
                        max_digits=6,
                    ),
                ),
            ],
            options={
                "ordering": ["actual_od", "label"],
            },
        ),
        migrations.AddField(
            model_name="weld",
            name="nominal_od",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Denormalized nominal pipe size label (e.g. 6")',
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="weld",
            name="wall_thickness_norm",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=3,
                help_text="Normalized wall thickness in inches rounded to 0.001",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["nominal_od"], name="welds_weld_nominal_b63d1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["wall_thickness_norm"], name="welds_weld_wall_th_decb13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["project", "nominal_od"], name="welds_weld_project_db51df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weld",
            index=models.Index(
                fields=["project", "wall_thickness_norm"],
                name="welds_weld_project_3dca5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weldrepair",
            index=models.Index(
                fields=["weld", "flagged_at"], name="welds_weldr_weld_id_0607ec_idx"
            ),
        ),
        migrations.AddField(
            model_name="nominalpipeod",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nominal_pipe_ods",
                to="organizations.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="nominalpipeod",
            constraint=models.UniqueConstraint(
                fields=("org", "actual_od"), name="unique_nominal_od_per_org"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nominalpipeod",
            unique_together={("org", "label")},
        ),
    ]
