# Generated by Django 4.2.25 on 2025-11-13 23:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welds", "0011_nominalpipeod_weld_nominal_od_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weld",
            name="nominal_od_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Actual OD (in) matched to the nominal size.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nominalpipeod",
            name="tolerance",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.010"),
                help_text="Allowable +/- tolerance when matching an actual OD.",
                max_digits=6,
            ),
        ),
    ]
