# Generated by Django 4.2.25 on 2025-11-13 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_alter_invitation_role_alter_membership_role_and_more"),
        ("drive", "0010_filenode_mtr_approved_filenode_mtr_approved_at_and_more"),
        ("welds", "0012_weld_nominal_od_actual_alter_nominalpipeod_tolerance"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialHeatDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parsed_at", models.DateTimeField(auto_now_add=True)),
                ("heat_number", models.CharField(blank=True, max_length=128)),
                ("material_description", models.CharField(blank=True, max_length=255)),
                ("material_type", models.CharField(blank=True, max_length=120)),
                ("material_grade", models.CharField(blank=True, max_length=120)),
                (
                    "outer_diameter_in",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "wall_thickness_in",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("wps_number", models.CharField(blank=True, max_length=128)),
                ("page_numbers", models.CharField(blank=True, max_length=255)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_heat_drafts",
                        to="drive.filenode",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_heat_drafts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parsed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parsed_material_heat_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_material_heat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="welds.materialheat",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_material_heat_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-parsed_at"],
                "indexes": [
                    models.Index(fields=["file_node"], name="mhd_file_node"),
                    models.Index(fields=["org", "verified"], name="mhd_org_verified"),
                ],
            },
        ),
    ]
