# Generated by Django 4.2.25 on 2025-11-13 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_planned_weld_inches_per_workday_and_more"),
        ("welds", "0013_materialheatdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialheat",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_heats",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="welder",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="welders",
                to="projects.project",
            ),
        ),
    ]
